SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM VENDEDORES;

UPDATE TABELA_DE_VENDEDORES SET DE_FERIAS = 0 WHERE MATRICULA IN ('00236', '00237');
UPDATE TABELA_DE_VENDEDORES SET DE_FERIAS = 1 WHERE MATRICULA IN ('00235', '00238');

INSERT INTO TABELA_DE_VENDEDORES (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS, BAIRRO)
VALUES ('00239', 'Jose', 0.12, TO_DATE('2018-01-01', 'YYYY-MM-DD'), 1, 'Tijuca');

-- RETORNA DADOS CUJAS MATRÍCULAS EXISTEM NAS DUAS TABELAS (COM INNER JOIN)
SELECT A.MATRICULA, B.MATRICULA, A.NOME, A.FERIAS, B.DE_FERIAS
FROM VENDEDORES A
INNER JOIN TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTR(B.MATRICULA, 3,3); -- RETORNA A PARTIR DO TERCEIRO CARACTERE (3,...) COM 3 CARACTERES (...,3)

-- RETORNA DADOS CUJAS MATRÍCULAS EXISTEM NAS DUAS TABELAS (COM EXISTS)
SELECT A.MATRICULA, A.NOME, A.FERIAS
FROM VENDEDORES A WHERE 
-- Substitui Inner Join
EXISTS (SELECT MATRICULA FROM TABELA_DE_VENDEDORES B
WHERE A.MATRICULA = SUBSTR (B.MATRICULA, 3,3)); -- CORREÇÃO DE NÚMERO DE MATRÍCULA


-- UPDATE QUE ALTERA STATUS DAS FÉRIAS DA TABELA 'VENDORES' PARA 
-- FICAR IGUAL AO DA 'TABELA_DE_VENDEDORES'
UPDATE VENDEDORES A SET A.FERIAS = 
-- retorna férias de funcionários da 'tabela_de_vendedores' cujas matrículas existem nas duas tabelas
(SELECT B.DE_FERIAS FROM TABELA_DE_VENDEDORES B
WHERE A.MATRICULA = SUBSTR (B.MATRICULA, 3,3))
-- onde as matrículas existem nas duas tabelas
WHERE EXISTS (SELECT MATRICULA FROM TABELA_DE_VENDEDORES B
WHERE A.MATRICULA = SUBSTR (B.MATRICULA, 3,3));

